/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bookinghotelsystem.MainPanel;


import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import javax.swing.UIManager;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/**
 *
 * @author Kevin
 */
public class MainWindow1 extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow1
     */
    
   
    
    public MainWindow1() {
        initComponents();
        //LoginSystem FIx BUG
        NumberSignUpInput.setVisible(false);
        UsernameSignUpInput.setVisible(false);
        PasswordSignUpInput.setVisible(false);
        PasswordSigninInput1.setVisible(false);
        UsernameSigninInput1.setVisible(false);
        
        
        try {
            connection();
        } catch (SQLException ex) {
            Logger.getLogger(MainWindow1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        MenuButtonsPanels.setVisible(false);
    }
    
    //Connection to database method ;>
    int LoginEnabled = 1;
     Connection con;
     Statement Stmt;
     PreparedStatement pst;
    
    //method for connection :>
    // "Db" means Database
    private static final String DbDriver = "com.mysql.cj.jdbc.Driver";
    private static final String DbURL = "jdbc:mysql://localhost:3306/hotelusers";
    private static final String DbPhoneNumber= "root";
    private static final String DbPassword = "";
    
    public void connection() throws SQLException {
        try {
            Class.forName(DbDriver);
            con = DriverManager.getConnection(DbURL, DbPhoneNumber, DbPassword);
            Stmt = con.createStatement();
            if (con != null) {
                System.out.println("Connection Success");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainWindow1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuButtonsPanels = new javax.swing.JPanel();
        UserNameGreetings = new javax.swing.JLabel();
        ViewHotelFeatureButton = new javax.swing.JButton();
        ExitMenuButton = new javax.swing.JButton();
        RoomSectionButtion = new javax.swing.JButton();
        ViewHotelFeatureButton1 = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        MainPanel1 = new javax.swing.JPanel();
        Decoration1 = new javax.swing.JPanel();
        jTextArea1 = new javax.swing.JTextArea();
        jTextArea3 = new javax.swing.JTextArea();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        Title1 = new javax.swing.JLabel();
        Title2 = new javax.swing.JLabel();
        Title3 = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        Background1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RoomInfoPanel = new javax.swing.JPanel();
        InfoWindow1 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jTextArea7 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        BookButton1 = new javax.swing.JButton();
        InfoWIndow3 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jTextArea9 = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        BookButton3 = new javax.swing.JButton();
        InfoWIndow2 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jTextArea8 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        BookButton2 = new javax.swing.JButton();
        RoomSectionPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        RoomBSelectionPanel2 = new javax.swing.JPanel();
        RoomB2S1 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        RoomB2Button1 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        RoomB1S1 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        RoomB1Button1 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        RoomBSelectionPanel1 = new javax.swing.JPanel();
        RoomB2S = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        RoomB2Button = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        RoomB1S = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        RoomB1Button = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        RoomASelectionPanel = new javax.swing.JPanel();
        RoomA2S = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        RoomA1Button1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        RoomA1S = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RoomA1Button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        MenuOpenButton = new javax.swing.JButton();
        CompanyNameLabel = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        LoginSystemPanel = new javax.swing.JPanel();
        LoginFormWindow = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        PasswordSigninInput1 = new javax.swing.JTextField();
        UsernameSigninInput1 = new javax.swing.JTextField();
        ExitLoginButton1 = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        SignInButton1 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        SignInButton2 = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        Background3 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        RegisterFormWindow = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        NumberSignUpInput = new javax.swing.JTextField();
        UsernameSignUpInput = new javax.swing.JTextField();
        PasswordSignUpInput = new javax.swing.JTextField();
        ExitLoginButton2 = new javax.swing.JButton();
        SignUpButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        GOSigninWindowButton = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        Background2 = new javax.swing.JLabel();
        AccountInfoWindow = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuButtonsPanels.setBackground(new java.awt.Color(213, 208, 153, 200));
        MenuButtonsPanels.setPreferredSize(new java.awt.Dimension(250, 500));
        MenuButtonsPanels.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserNameGreetings.setBackground(new java.awt.Color(255, 255, 255));
        UserNameGreetings.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        UserNameGreetings.setForeground(new java.awt.Color(255, 255, 255));
        UserNameGreetings.setText("Username!");
        MenuButtonsPanels.add(UserNameGreetings, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 200, 20));

        ViewHotelFeatureButton.setBackground(new java.awt.Color(209, 199, 155));
        ViewHotelFeatureButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ViewHotelFeatureButton.setForeground(new java.awt.Color(255, 255, 255));
        ViewHotelFeatureButton.setText("Account/User");
        ViewHotelFeatureButton.setBorder(null);
        ViewHotelFeatureButton.setBorderPainted(false);
        ViewHotelFeatureButton.setContentAreaFilled(false);
        ViewHotelFeatureButton.setFocusPainted(false);
        ViewHotelFeatureButton.setFocusable(false);
        ViewHotelFeatureButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ViewHotelFeatureButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ViewHotelFeatureButton.setOpaque(true);
        ViewHotelFeatureButton.setRolloverEnabled(false);
        ViewHotelFeatureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewHotelFeatureButtonActionPerformed(evt);
            }
        });
        MenuButtonsPanels.add(ViewHotelFeatureButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 250, 40));

        ExitMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BookingHotelSystemIcons/Logo1-removebg-preview - 40x40.png"))); // NOI18N
        ExitMenuButton.setBorder(null);
        ExitMenuButton.setBorderPainted(false);
        ExitMenuButton.setContentAreaFilled(false);
        ExitMenuButton.setFocusPainted(false);
        ExitMenuButton.setFocusable(false);
        ExitMenuButton.setRolloverEnabled(false);
        ExitMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMenuButtonActionPerformed(evt);
            }
        });
        MenuButtonsPanels.add(ExitMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        RoomSectionButtion.setBackground(new java.awt.Color(209, 199, 155));
        RoomSectionButtion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        RoomSectionButtion.setForeground(new java.awt.Color(255, 255, 255));
        RoomSectionButtion.setText("Available Rooms");
        RoomSectionButtion.setBorder(null);
        RoomSectionButtion.setBorderPainted(false);
        RoomSectionButtion.setContentAreaFilled(false);
        RoomSectionButtion.setFocusPainted(false);
        RoomSectionButtion.setFocusable(false);
        RoomSectionButtion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RoomSectionButtion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RoomSectionButtion.setOpaque(true);
        RoomSectionButtion.setRolloverEnabled(false);
        RoomSectionButtion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomSectionButtionActionPerformed(evt);
            }
        });
        MenuButtonsPanels.add(RoomSectionButtion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 250, 40));

        ViewHotelFeatureButton1.setBackground(new java.awt.Color(209, 199, 155));
        ViewHotelFeatureButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ViewHotelFeatureButton1.setForeground(new java.awt.Color(255, 255, 255));
        ViewHotelFeatureButton1.setText("Hotel Essentials");
        ViewHotelFeatureButton1.setBorder(null);
        ViewHotelFeatureButton1.setBorderPainted(false);
        ViewHotelFeatureButton1.setContentAreaFilled(false);
        ViewHotelFeatureButton1.setFocusPainted(false);
        ViewHotelFeatureButton1.setFocusable(false);
        ViewHotelFeatureButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ViewHotelFeatureButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ViewHotelFeatureButton1.setOpaque(true);
        ViewHotelFeatureButton1.setRolloverEnabled(false);
        ViewHotelFeatureButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewHotelFeatureButton1ActionPerformed(evt);
            }
        });
        MenuButtonsPanels.add(ViewHotelFeatureButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 250, 40));

        jLabel43.setBackground(new java.awt.Color(255, 255, 255));
        jLabel43.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Welcome to Auqeza");
        MenuButtonsPanels.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 200, 20));

        getContentPane().add(MenuButtonsPanels, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        MainPanel1.setEnabled(false);
        MainPanel1.setOpaque(false);
        MainPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Decoration1.setPreferredSize(new java.awt.Dimension(750, 3));

        javax.swing.GroupLayout Decoration1Layout = new javax.swing.GroupLayout(Decoration1);
        Decoration1.setLayout(Decoration1Layout);
        Decoration1Layout.setHorizontalGroup(
            Decoration1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        Decoration1Layout.setVerticalGroup(
            Decoration1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        MainPanel1.add(Decoration1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 90, 760, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(204, 204, 204,0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Convenient location,\nfast Wi-Fi, and \nmeeting spaces for\nprofessionals on the\ngo.");
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setBorder(null);
        jTextArea1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTextArea1.setDoubleBuffered(true);
        jTextArea1.setFocusable(false);
        jTextArea1.setOpaque(false);
        MainPanel1.add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 240, -1));

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("Reliable room service, \ngyms, pools, dining \nareas pact with buffet\ndishes from \nprofessional chefs,\nsuitable for a guest's \ndaily needs.\n");
        jTextArea3.setAutoscrolls(false);
        jTextArea3.setBorder(null);
        jTextArea3.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTextArea3.setDoubleBuffered(true);
        jTextArea3.setFocusable(false);
        jTextArea3.setOpaque(false);
        MainPanel1.add(jTextArea3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 240, -1));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("Modern rooms, top \nnotch amenities,\nand breathtaking \nviews for a perfect \nview.\n");
        jTextArea2.setAutoscrolls(false);
        jTextArea2.setBorder(null);
        jTextArea2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTextArea2.setDoubleBuffered(true);
        jTextArea2.setFocusable(false);
        jTextArea2.setOpaque(false);
        MainPanel1.add(jTextArea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 240, -1));

        jButton1.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Find room");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        MainPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 180, 50));

        Title1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        Title1.setForeground(new java.awt.Color(248, 245, 222));
        Title1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Title1.setText("Luxury Escape");
        Title1.setPreferredSize(new java.awt.Dimension(300, 50));
        MainPanel1.add(Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 90, -1, -1));

        Title2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        Title2.setForeground(new java.awt.Color(248, 245, 222));
        Title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title2.setText("Features");
        Title2.setPreferredSize(new java.awt.Dimension(300, 50));
        MainPanel1.add(Title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 90, -1, -1));

        Title3.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        Title3.setForeground(new java.awt.Color(248, 245, 222));
        Title3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title3.setText("Business Hub");
        Title3.setPreferredSize(new java.awt.Dimension(300, 50));
        MainPanel1.add(Title3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        Title.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(248, 245, 222));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Welcome to Auqeza Suites");
        Title.setPreferredSize(new java.awt.Dimension(750, 50));
        MainPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 450, -1));

        Logo.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        Logo.setForeground(new java.awt.Color(248, 245, 222));
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BookingHotelSystemIcons/Logo1-removebg-preview - 40x40.png"))); // NOI18N
        Logo.setPreferredSize(new java.awt.Dimension(50, 50));
        MainPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 60, 50));

        Background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookinghotelsystem/PicturesforIcons/MainSystemPictures/Room View None.jpg"))); // NOI18N
        Background1.setPreferredSize(new java.awt.Dimension(1000, 500));
        MainPanel1.add(Background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setPreferredSize(new java.awt.Dimension(1000, 500));
        MainPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(MainPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        RoomInfoPanel.setPreferredSize(new java.awt.Dimension(1000, 500));

        InfoWindow1.setBackground(new java.awt.Color(102, 102, 102));
        InfoWindow1.setPreferredSize(new java.awt.Dimension(1000, 500));
        InfoWindow1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InfoRoomPics/InfoPic1.jpg"))); // NOI18N
        InfoWindow1.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jTextArea7.setEditable(false);
        jTextArea7.setColumns(20);
        jTextArea7.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jTextArea7.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea7.setLineWrap(true);
        jTextArea7.setRows(5);
        jTextArea7.setText("- Size: 25 sqm\n- Pax/Capacity: 2 guests\n- Bed Type: 1 queen bed\n- Amanities: free wifi, air conditioning, smart tv, \n- Private, bathroom with hot & cold shower,\n  complimentry toilets\n- Price per night: PHP 10,500 \n- Price per day: PHP 20,500 \n\n");
        jTextArea7.setFocusable(false);
        jTextArea7.setOpaque(false);
        InfoWindow1.add(jTextArea7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 470, 200));

        jPanel4.setPreferredSize(new java.awt.Dimension(450, 3));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        InfoWindow1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, -1));

        jLabel51.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("DELUXE ROOM");
        jLabel51.setToolTipText("");
        InfoWindow1.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 420, 40));

        BookButton1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        BookButton1.setForeground(new java.awt.Color(255, 255, 255));
        BookButton1.setText("Book this room");
        BookButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        BookButton1.setContentAreaFilled(false);
        BookButton1.setFocusable(false);
        BookButton1.setPreferredSize(new java.awt.Dimension(250, 50));
        BookButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookButton1ActionPerformed(evt);
            }
        });
        InfoWindow1.add(BookButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 380, -1, -1));

        InfoWIndow3.setBackground(new java.awt.Color(102, 102, 102));
        InfoWIndow3.setPreferredSize(new java.awt.Dimension(1000, 500));
        InfoWIndow3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InfoRoomPics/InfoPic12nd.jpg"))); // NOI18N
        InfoWIndow3.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jTextArea9.setEditable(false);
        jTextArea9.setColumns(20);
        jTextArea9.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jTextArea9.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea9.setLineWrap(true);
        jTextArea9.setRows(5);
        jTextArea9.setText("- Size: 45 sqm\n- Capacity/Pax: 4 guests\n- Bed Type: 2 Queen Beds\n- Amenities: Free WiFi, Air Conditioning, 50” Smart TV,  Living Area, Dining Table, Mini Bar, Private Balcony \n with City View\n Complimentary Breakfast\n- Price per Night: PHP 45,500\n- Price per Day: PHP 50,500");
        jTextArea9.setFocusable(false);
        jTextArea9.setOpaque(false);
        InfoWIndow3.add(jTextArea9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 470, 200));

        jPanel7.setPreferredSize(new java.awt.Dimension(450, 3));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        InfoWIndow3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, -1));

        jLabel56.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("PRESIDENTIAL SUITE");
        jLabel56.setToolTipText("");
        InfoWIndow3.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 420, 40));

        BookButton3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        BookButton3.setForeground(new java.awt.Color(255, 255, 255));
        BookButton3.setText("Book this room");
        BookButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        BookButton3.setContentAreaFilled(false);
        BookButton3.setFocusable(false);
        BookButton3.setPreferredSize(new java.awt.Dimension(250, 50));
        InfoWIndow3.add(BookButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 380, -1, -1));

        InfoWIndow2.setBackground(new java.awt.Color(102, 102, 102));
        InfoWIndow2.setPreferredSize(new java.awt.Dimension(1000, 500));
        InfoWIndow2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InfoRoomPics/InfoPic2.jpg"))); // NOI18N
        InfoWIndow2.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jTextArea8.setEditable(false);
        jTextArea8.setColumns(20);
        jTextArea8.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jTextArea8.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea8.setLineWrap(true);
        jTextArea8.setRows(5);
        jTextArea8.setText("- Size: 45 sqm\n- Capacity/Pax: 4 guests\n- Bed Type: 2 Queen Beds\n- Amenities: Free WiFi, Air Conditioning, 50” Smart TV,  Living Area, Dining Table, Mini Bar, Private Balcony \n with City View\n Complimentary Breakfast\n- Price per Night: PHP 3,500\n- Price per Day: PHP 5,500");
        jTextArea8.setFocusable(false);
        jTextArea8.setOpaque(false);
        InfoWIndow2.add(jTextArea8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 470, 200));

        jPanel6.setPreferredSize(new java.awt.Dimension(450, 3));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        InfoWIndow2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, -1));

        jLabel54.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("FAMILY ROOM");
        jLabel54.setToolTipText("");
        InfoWIndow2.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 420, 40));

        BookButton2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        BookButton2.setForeground(new java.awt.Color(255, 255, 255));
        BookButton2.setText("Book this room");
        BookButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        BookButton2.setContentAreaFilled(false);
        BookButton2.setFocusable(false);
        BookButton2.setPreferredSize(new java.awt.Dimension(250, 50));
        InfoWIndow2.add(BookButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 380, -1, -1));

        javax.swing.GroupLayout RoomInfoPanelLayout = new javax.swing.GroupLayout(RoomInfoPanel);
        RoomInfoPanel.setLayout(RoomInfoPanelLayout);
        RoomInfoPanelLayout.setHorizontalGroup(
            RoomInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(RoomInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RoomInfoPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(RoomInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(InfoWindow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(InfoWIndow2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(RoomInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RoomInfoPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InfoWIndow3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        RoomInfoPanelLayout.setVerticalGroup(
            RoomInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(RoomInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RoomInfoPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(RoomInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(InfoWindow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(InfoWIndow2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(RoomInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RoomInfoPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InfoWIndow3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(RoomInfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        RoomSectionPanel.setOpaque(false);
        RoomSectionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setFocusable(false);
        jScrollPane2.setOpaque(false);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(1000, 460));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setDoubleBuffered(false);
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(998, 1130));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RoomBSelectionPanel2.setBackground(new java.awt.Color(0, 0, 0));
        RoomBSelectionPanel2.setOpaque(false);
        RoomBSelectionPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RoomB2S1.setBackground(new java.awt.Color(238, 236, 200, 90));
        RoomB2S1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomPicturesABC/MainRoomA2.jpg"))); // NOI18N
        jLabel33.setText("jLabel1");
        jLabel33.setPreferredSize(new java.awt.Dimension(200, 200));
        RoomB2S1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 200));

        RoomB2Button1.setBackground(new java.awt.Color(228, 223, 192));
        RoomB2Button1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RoomB2Button1.setForeground(new java.awt.Color(103, 102, 54));
        RoomB2Button1.setText("See room info");
        RoomB2Button1.setBorderPainted(false);
        RoomB2Button1.setFocusable(false);
        RoomB2Button1.setPreferredSize(new java.awt.Dimension(150, 25));
        RoomB2Button1.setRolloverEnabled(false);
        RoomB2S1.add(RoomB2Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, 30));

        jLabel34.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel34.setText("3 rooms Available");
        RoomB2S1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 20));

        jLabel35.setBackground(new java.awt.Color(238, 236, 200));
        jLabel35.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(238, 236, 200));
        jLabel35.setText("Double Business B");
        RoomB2S1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 30));

        jLabel36.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 255, 0));
        jLabel36.setText("₱ 2,499 per night");
        RoomB2S1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, 20));

        RoomBSelectionPanel2.add(RoomB2S1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        RoomB1S1.setBackground(new java.awt.Color(238, 236, 200, 90));
        RoomB1S1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomPicturesABC/MainRoomA1.jpg"))); // NOI18N
        jLabel37.setText("jLabel1");
        jLabel37.setPreferredSize(new java.awt.Dimension(200, 200));
        RoomB1S1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 200));

        RoomB1Button1.setBackground(new java.awt.Color(228, 223, 192));
        RoomB1Button1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RoomB1Button1.setForeground(new java.awt.Color(103, 102, 54));
        RoomB1Button1.setText("See room info");
        RoomB1Button1.setBorderPainted(false);
        RoomB1Button1.setFocusable(false);
        RoomB1Button1.setPreferredSize(new java.awt.Dimension(150, 25));
        RoomB1Button1.setRequestFocusEnabled(false);
        RoomB1Button1.setRolloverEnabled(false);
        RoomB1S1.add(RoomB1Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, 30));

        jLabel38.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel38.setText("3 rooms Available");
        RoomB1S1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 20));

        jLabel39.setBackground(new java.awt.Color(238, 236, 200));
        jLabel39.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(238, 236, 200));
        jLabel39.setText("Single Business B");
        RoomB1S1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 30));

        jLabel40.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 255, 0));
        jLabel40.setText("₱ 1,500 per night");
        RoomB1S1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, 20));

        RoomBSelectionPanel2.add(RoomB1S1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel41.setBackground(new java.awt.Color(238, 236, 200));
        jLabel41.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(238, 236, 200));
        jLabel41.setText("Presidential Suites");
        RoomBSelectionPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 820, 50));

        jPanel1.add(RoomBSelectionPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 740, 950, -1));

        RoomBSelectionPanel1.setBackground(new java.awt.Color(0, 0, 0));
        RoomBSelectionPanel1.setOpaque(false);
        RoomBSelectionPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RoomB2S.setBackground(new java.awt.Color(238, 236, 200, 90));
        RoomB2S.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomPicturesABC/MainRoomA2.jpg"))); // NOI18N
        jLabel16.setText("jLabel1");
        jLabel16.setPreferredSize(new java.awt.Dimension(200, 200));
        RoomB2S.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 200));

        RoomB2Button.setBackground(new java.awt.Color(228, 223, 192));
        RoomB2Button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RoomB2Button.setForeground(new java.awt.Color(103, 102, 54));
        RoomB2Button.setText("See room info");
        RoomB2Button.setBorderPainted(false);
        RoomB2Button.setFocusable(false);
        RoomB2Button.setPreferredSize(new java.awt.Dimension(150, 25));
        RoomB2Button.setRolloverEnabled(false);
        RoomB2S.add(RoomB2Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, 30));

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel17.setText("3 rooms Available");
        RoomB2S.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 20));

        jLabel18.setBackground(new java.awt.Color(238, 236, 200));
        jLabel18.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(238, 236, 200));
        jLabel18.setText("Double Business B");
        RoomB2S.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 30));

        jLabel27.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 255, 0));
        jLabel27.setText("₱ 2,499 per night");
        RoomB2S.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, 20));

        RoomBSelectionPanel1.add(RoomB2S, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        RoomB1S.setBackground(new java.awt.Color(238, 236, 200, 90));
        RoomB1S.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomPicturesABC/MainRoomA1.jpg"))); // NOI18N
        jLabel19.setText("jLabel1");
        jLabel19.setPreferredSize(new java.awt.Dimension(200, 200));
        RoomB1S.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 200));

        RoomB1Button.setBackground(new java.awt.Color(228, 223, 192));
        RoomB1Button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RoomB1Button.setForeground(new java.awt.Color(103, 102, 54));
        RoomB1Button.setText("See room info");
        RoomB1Button.setBorderPainted(false);
        RoomB1Button.setFocusable(false);
        RoomB1Button.setPreferredSize(new java.awt.Dimension(150, 25));
        RoomB1Button.setRequestFocusEnabled(false);
        RoomB1Button.setRolloverEnabled(false);
        RoomB1S.add(RoomB1Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, 30));

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel20.setText("3 rooms Available");
        RoomB1S.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 20));

        jLabel21.setBackground(new java.awt.Color(238, 236, 200));
        jLabel21.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(238, 236, 200));
        jLabel21.setText("Single Business B");
        RoomB1S.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 30));

        jLabel28.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 255, 0));
        jLabel28.setText("₱ 1,500 per night");
        RoomB1S.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, 20));

        RoomBSelectionPanel1.add(RoomB1S, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel22.setBackground(new java.awt.Color(238, 236, 200));
        jLabel22.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(238, 236, 200));
        jLabel22.setText("Family Class Rooms");
        RoomBSelectionPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 820, 50));

        jPanel1.add(RoomBSelectionPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 950, -1));

        RoomASelectionPanel.setBackground(new java.awt.Color(0, 0, 0));
        RoomASelectionPanel.setOpaque(false);
        RoomASelectionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RoomA2S.setBackground(new java.awt.Color(238, 236, 200, 90));
        RoomA2S.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomPicturesABC/MainRoomA2.jpg"))); // NOI18N
        jLabel5.setText("jLabel1");
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 200));
        RoomA2S.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 200));

        RoomA1Button1.setBackground(new java.awt.Color(228, 223, 192));
        RoomA1Button1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RoomA1Button1.setForeground(new java.awt.Color(103, 102, 54));
        RoomA1Button1.setText("See room info");
        RoomA1Button1.setBorderPainted(false);
        RoomA1Button1.setFocusable(false);
        RoomA1Button1.setPreferredSize(new java.awt.Dimension(150, 25));
        RoomA1Button1.setRolloverEnabled(false);
        RoomA2S.add(RoomA1Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, 30));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("3 rooms Available");
        RoomA2S.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 20));

        jLabel7.setBackground(new java.awt.Color(238, 236, 200));
        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(238, 236, 200));
        jLabel7.setText("Double Class A");
        RoomA2S.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 30));

        jLabel24.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 255, 0));
        jLabel24.setText("₱ 2,499 per night");
        RoomA2S.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, 20));

        RoomASelectionPanel.add(RoomA2S, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        RoomA1S.setBackground(new java.awt.Color(238, 236, 200, 90));
        RoomA1S.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomPicturesABC/MainRoomA1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 200));
        RoomA1S.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 200));

        RoomA1Button.setBackground(new java.awt.Color(228, 223, 192));
        RoomA1Button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RoomA1Button.setForeground(new java.awt.Color(103, 102, 54));
        RoomA1Button.setText("See room info");
        RoomA1Button.setBorderPainted(false);
        RoomA1Button.setFocusable(false);
        RoomA1Button.setPreferredSize(new java.awt.Dimension(150, 25));
        RoomA1Button.setRequestFocusEnabled(false);
        RoomA1Button.setRolloverEnabled(false);
        RoomA1S.add(RoomA1Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, 30));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("3 rooms Available");
        RoomA1S.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 20));

        jLabel4.setBackground(new java.awt.Color(238, 236, 200));
        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(238, 236, 200));
        jLabel4.setText("Single Class A");
        RoomA1S.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 30));

        jLabel23.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 255, 0));
        jLabel23.setText("₱ 1,500 per night");
        RoomA1S.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, 20));

        RoomASelectionPanel.add(RoomA1S, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel11.setBackground(new java.awt.Color(238, 236, 200));
        jLabel11.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(238, 236, 200));
        jLabel11.setText("Deluxe Class Rooms");
        RoomASelectionPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 820, 50));

        jPanel1.add(RoomASelectionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0, 70));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1140, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane2.setViewportView(jPanel1);

        RoomSectionPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        MenuOpenButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BookingHotelSystemIcons/Logo1-removebg-preview - 40x40.png"))); // NOI18N
        MenuOpenButton.setBorder(null);
        MenuOpenButton.setBorderPainted(false);
        MenuOpenButton.setContentAreaFilled(false);
        MenuOpenButton.setFocusPainted(false);
        MenuOpenButton.setRolloverEnabled(false);
        MenuOpenButton.setVerifyInputWhenFocusTarget(false);
        MenuOpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOpenButtonActionPerformed(evt);
            }
        });
        RoomSectionPanel.add(MenuOpenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        CompanyNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        CompanyNameLabel.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        CompanyNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        CompanyNameLabel.setText("Auqeza Suites");
        RoomSectionPanel.add(CompanyNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 820, 40));

        Background.setBackground(new java.awt.Color(0, 0, 0));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookinghotelsystem/PicturesforIcons/MainSystemPictures/Room View Main Intro Blurred100.jpg"))); // NOI18N
        Background.setPreferredSize(new java.awt.Dimension(1000, 500));
        RoomSectionPanel.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(RoomSectionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        LoginSystemPanel.setBackground(new java.awt.Color(235, 231, 203));
        LoginSystemPanel.setPreferredSize(new java.awt.Dimension(1000, 500));
        LoginSystemPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginFormWindow.setBackground(new java.awt.Color(255, 255, 255));
        LoginFormWindow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(182, 170, 147), 3));
        LoginFormWindow.setPreferredSize(new java.awt.Dimension(500, 300));
        LoginFormWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel60.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("Sign in to Auqeza Suites");
        LoginFormWindow.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 270, 30));

        PasswordSigninInput1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        PasswordSigninInput1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 196, 173), 2));
        PasswordSigninInput1.setFocusTraversalPolicyProvider(true);
        PasswordSigninInput1.setInheritsPopupMenu(true);
        PasswordSigninInput1.setPreferredSize(new java.awt.Dimension(250, 35));
        PasswordSigninInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordSigninInput1ActionPerformed(evt);
            }
        });
        LoginFormWindow.add(PasswordSigninInput1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 220, -1, -1));

        UsernameSigninInput1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        UsernameSigninInput1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 196, 173), 2));
        UsernameSigninInput1.setFocusTraversalPolicyProvider(true);
        UsernameSigninInput1.setInheritsPopupMenu(true);
        UsernameSigninInput1.setPreferredSize(new java.awt.Dimension(250, 35));
        UsernameSigninInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameSigninInput1ActionPerformed(evt);
            }
        });
        LoginFormWindow.add(UsernameSigninInput1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, -1, -1));

        ExitLoginButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ExitLoginButton1.setText("Exit");
        ExitLoginButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(182, 174, 140), 2));
        ExitLoginButton1.setFocusPainted(false);
        ExitLoginButton1.setFocusTraversalPolicyProvider(true);
        ExitLoginButton1.setFocusable(false);
        ExitLoginButton1.setPreferredSize(new java.awt.Dimension(100, 35));
        ExitLoginButton1.setRequestFocusEnabled(false);
        ExitLoginButton1.setVerifyInputWhenFocusTarget(false);
        ExitLoginButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitLoginButton1ActionPerformed(evt);
            }
        });
        LoginFormWindow.add(ExitLoginButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, -1, -1));

        jLabel45.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel45.setText("Doesnt have an account yet?");
        LoginFormWindow.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, 160, 30));

        SignInButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        SignInButton1.setText("Create Account");
        SignInButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(182, 174, 140), 2));
        SignInButton1.setFocusPainted(false);
        SignInButton1.setPreferredSize(new java.awt.Dimension(100, 35));
        SignInButton1.setRequestFocusEnabled(false);
        SignInButton1.setRolloverEnabled(false);
        SignInButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInButton1ActionPerformed(evt);
            }
        });
        LoginFormWindow.add(SignInButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 430, 150, -1));

        jLabel47.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel47.setText("Phone number:");
        LoginFormWindow.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 140, 30));

        SignInButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        SignInButton2.setText("Sign in");
        SignInButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(182, 174, 140), 2));
        SignInButton2.setFocusable(false);
        SignInButton2.setPreferredSize(new java.awt.Dimension(100, 35));
        SignInButton2.setRequestFocusEnabled(false);
        SignInButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInButton2ActionPerformed(evt);
            }
        });
        LoginFormWindow.add(SignInButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 380, -1, -1));

        jLabel50.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel50.setText("Password:");
        LoginFormWindow.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 140, 30));

        Background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookinghotelsystem/PicturesforIcons/MainSystemPictures/Room View None.jpg"))); // NOI18N
        Background3.setPreferredSize(new java.awt.Dimension(1000, 500));
        LoginFormWindow.add(Background3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, -1));

        jLabel59.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel59.setText("Sign in to Auqeza Suites");
        LoginFormWindow.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 30));

        LoginSystemPanel.add(LoginFormWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        RegisterFormWindow.setBackground(new java.awt.Color(255, 255, 255));
        RegisterFormWindow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(182, 170, 147), 3));
        RegisterFormWindow.setPreferredSize(new java.awt.Dimension(500, 300));
        RegisterFormWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Auqeza Suites");
        RegisterFormWindow.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 30));

        NumberSignUpInput.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        NumberSignUpInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 196, 173), 2));
        NumberSignUpInput.setFocusCycleRoot(true);
        NumberSignUpInput.setInheritsPopupMenu(true);
        NumberSignUpInput.setPreferredSize(new java.awt.Dimension(250, 35));
        NumberSignUpInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberSignUpInputActionPerformed(evt);
            }
        });
        RegisterFormWindow.add(NumberSignUpInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, -1, -1));

        UsernameSignUpInput.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        UsernameSignUpInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 196, 173), 2));
        UsernameSignUpInput.setFocusCycleRoot(true);
        UsernameSignUpInput.setInheritsPopupMenu(true);
        UsernameSignUpInput.setPreferredSize(new java.awt.Dimension(250, 35));
        UsernameSignUpInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameSignUpInputActionPerformed(evt);
            }
        });
        RegisterFormWindow.add(UsernameSignUpInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, -1, -1));

        PasswordSignUpInput.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        PasswordSignUpInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 196, 173), 2));
        PasswordSignUpInput.setFocusCycleRoot(true);
        PasswordSignUpInput.setInheritsPopupMenu(true);
        PasswordSignUpInput.setPreferredSize(new java.awt.Dimension(250, 35));
        PasswordSignUpInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordSignUpInputActionPerformed(evt);
            }
        });
        RegisterFormWindow.add(PasswordSignUpInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, -1, -1));

        ExitLoginButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ExitLoginButton2.setText("Exit");
        ExitLoginButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(182, 174, 140), 2));
        ExitLoginButton2.setFocusPainted(false);
        ExitLoginButton2.setFocusable(false);
        ExitLoginButton2.setPreferredSize(new java.awt.Dimension(100, 35));
        ExitLoginButton2.setRequestFocusEnabled(false);
        ExitLoginButton2.setVerifyInputWhenFocusTarget(false);
        ExitLoginButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitLoginButton2ActionPerformed(evt);
            }
        });
        RegisterFormWindow.add(ExitLoginButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, -1, -1));

        SignUpButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        SignUpButton1.setText("Create Account");
        SignUpButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(182, 174, 140), 2));
        SignUpButton1.setFocusPainted(false);
        SignUpButton1.setPreferredSize(new java.awt.Dimension(100, 35));
        SignUpButton1.setRequestFocusEnabled(false);
        SignUpButton1.setRolloverEnabled(false);
        SignUpButton1.setVerifyInputWhenFocusTarget(false);
        SignUpButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButton1ActionPerformed(evt);
            }
        });
        RegisterFormWindow.add(SignUpButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 390, 170, -1));

        jLabel13.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel13.setText("Username:");
        RegisterFormWindow.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 140, 30));

        jLabel58.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel58.setText("Register");
        RegisterFormWindow.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 290, 30));

        jLabel44.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel44.setText("Already have an account?");
        RegisterFormWindow.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 440, 140, 30));

        jLabel48.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel48.setText("Password:");
        RegisterFormWindow.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 140, 30));

        GOSigninWindowButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        GOSigninWindowButton.setText("Sign In");
        GOSigninWindowButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(182, 174, 140), 2));
        GOSigninWindowButton.setFocusable(false);
        GOSigninWindowButton.setPreferredSize(new java.awt.Dimension(100, 35));
        GOSigninWindowButton.setRequestFocusEnabled(false);
        GOSigninWindowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GOSigninWindowButtonActionPerformed(evt);
            }
        });
        RegisterFormWindow.add(GOSigninWindowButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 440, -1, -1));

        jLabel49.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel49.setText("Phone number:");
        RegisterFormWindow.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 140, 30));

        Background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookinghotelsystem/PicturesforIcons/MainSystemPictures/Room View None.jpg"))); // NOI18N
        Background2.setPreferredSize(new java.awt.Dimension(1000, 500));
        RegisterFormWindow.add(Background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, -1));

        LoginSystemPanel.add(RegisterFormWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        getContentPane().add(LoginSystemPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        AccountInfoWindow.setPreferredSize(new java.awt.Dimension(1000, 500));

        jLabel57.setText("Accoujnt");

        javax.swing.GroupLayout AccountInfoWindowLayout = new javax.swing.GroupLayout(AccountInfoWindow);
        AccountInfoWindow.setLayout(AccountInfoWindowLayout);
        AccountInfoWindowLayout.setHorizontalGroup(
            AccountInfoWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountInfoWindowLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(443, Short.MAX_VALUE))
        );
        AccountInfoWindowLayout.setVerticalGroup(
            AccountInfoWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountInfoWindowLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(393, Short.MAX_VALUE))
        );

        getContentPane().add(AccountInfoWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Book button on Start
        if (LoginEnabled < 2) {
        MainPanel1.setVisible(false);
        MenuButtonsPanels.setVisible(false);
        RoomSectionPanel.setVisible(false);
        RoomInfoPanel.setVisible(false);
        //Opening main Login Window
        LoginSystemPanel.setVisible(true);
        RegisterFormWindow.setVisible(false);
        LoginFormWindow.setVisible(true);
        PasswordSigninInput1.setVisible(true);
        UsernameSigninInput1.setVisible(true);

    } else {
        jScrollPane2.setVisible(false);
        RoomSectionPanel.setVisible(true);
        MainPanel1.setVisible(false);
        jButton1.setVisible(false);
        
        Timer timer1 = new Timer(500, e -> {
            jScrollPane2.setVisible(true);
            jScrollPane2.setOpaque(false);
            jScrollPane2.getViewport().setOpaque(false);
        });
        timer1.setRepeats(false);
        timer1.start();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void ViewHotelFeatureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewHotelFeatureButtonActionPerformed
        // Side Panel Open Account details
        if (LoginEnabled < 2) {
            //turning off Panels
            MainPanel1.setVisible(false);
            MenuButtonsPanels.setVisible(false);
            RoomSectionPanel.setVisible(false);
            RoomInfoPanel.setVisible(false);
            //Opening main Login Window
            LoginSystemPanel.setVisible(true);
            RegisterFormWindow.setVisible(false);
            LoginFormWindow.setVisible(true);
            
        } else {
            //turning off Panels
            MainPanel1.setVisible(false);
            MenuButtonsPanels.setVisible(false);
            RoomSectionPanel.setVisible(false);
            RoomInfoPanel.setVisible(false);
            //Opening Main Window Account
            LoginSystemPanel.setVisible(true);
        }
    }//GEN-LAST:event_ViewHotelFeatureButtonActionPerformed

    private void RoomSectionButtionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomSectionButtionActionPerformed

       
        
    }//GEN-LAST:event_RoomSectionButtionActionPerformed

    private void ViewHotelFeatureButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewHotelFeatureButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewHotelFeatureButton1ActionPerformed

    private void ExitMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuButtonActionPerformed
        MenuButtonsPanels.setVisible(false);
        CompanyNameLabel.setVisible(true);
    }//GEN-LAST:event_ExitMenuButtonActionPerformed

    private void MenuOpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOpenButtonActionPerformed
        MenuButtonsPanels.setVisible(true);
        CompanyNameLabel.setVisible(false);
    }//GEN-LAST:event_MenuOpenButtonActionPerformed

    private void PasswordSigninInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordSigninInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordSigninInput1ActionPerformed

    private void UsernameSigninInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameSigninInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameSigninInput1ActionPerformed

    private void ExitLoginButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitLoginButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitLoginButton1ActionPerformed

    private void SignInButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInButton1ActionPerformed
        //going to signupWindow
        RegisterFormWindow.setVisible(true);
        NumberSignUpInput.setVisible(true);
        UsernameSignUpInput.setVisible(true);
        PasswordSignUpInput.setVisible(true);
        LoginFormWindow.setVisible(false);
        PasswordSigninInput1.setVisible(false);
        UsernameSigninInput1.setVisible(false);
    }//GEN-LAST:event_SignInButton1ActionPerformed

    private void SignInButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInButton2ActionPerformed
         //Signing In your Account code :>
         String Phonenumber, password;
         Phonenumber = UsernameSigninInput1.getText();
         password = PasswordSigninInput1.getText();
         String queryLogin = "SELECT * FROM hotelusersdatabase WHERE PhoneNumber = '" + Phonenumber + "' AND Password = '" + password + "'";
         String query1 = "SELECT Username FROM hotelusersdatabase WHERE PhoneNumber = ? AND Password = ?";
         try {
            pst = con.prepareStatement(queryLogin);
            ResultSet rs = pst.executeQuery();
            if(!rs.next()) {
                JOptionPane.showMessageDialog(null, "Invalid Credentials");
                
            } else {
                JOptionPane.showMessageDialog(null, "Successfull Login!");
                LoginEnabled = 3;
                UsernameSigninInput1.setText("");
                PasswordSigninInput1.setText("");
                String username1 = rs.getString("Username");
                UserNameGreetings.setText(username1 + "!");
                //loginscreen false4
                LoginFormWindow.setVisible(false);
                PasswordSigninInput1.setVisible(false);
                UsernameSigninInput1.setVisible(false);
                RegisterFormWindow.setVisible(false);
                NumberSignUpInput.setVisible(false);
                UsernameSignUpInput.setVisible(false);
                PasswordSignUpInput.setVisible(false);
                RoomSectionPanel.setVisible(true);

                
                
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainWindow1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         
        
    }//GEN-LAST:event_SignInButton2ActionPerformed

    private void BookButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookButton1ActionPerformed
        // TODO add your handling code here:
        if (LoginEnabled < 2) {
            //turning off Panels
            MainPanel1.setVisible(false);
            MenuButtonsPanels.setVisible(false);
            RoomSectionPanel.setVisible(false);
            RoomInfoPanel.setVisible(false);
            //Opening main Login Window
            LoginSystemPanel.setVisible(true);
            RegisterFormWindow.setVisible(false);
            LoginFormWindow.setVisible(true);
            
        } else {
            //turning off Panels
            MainPanel1.setVisible(false);
            MenuButtonsPanels.setVisible(false);
            RoomSectionPanel.setVisible(false);
            RoomInfoPanel.setVisible(false);
            //Opening Main Window Account
            LoginSystemPanel.setVisible(true);
        }
    }//GEN-LAST:event_BookButton1ActionPerformed

    private void NumberSignUpInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberSignUpInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberSignUpInputActionPerformed

    private void UsernameSignUpInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameSignUpInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameSignUpInputActionPerformed

    private void PasswordSignUpInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordSignUpInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordSignUpInputActionPerformed

    private void ExitLoginButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitLoginButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitLoginButton2ActionPerformed

    private void SignUpButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpButton1ActionPerformed

    private void GOSigninWindowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GOSigninWindowButtonActionPerformed
        //going to sign in window
        RegisterFormWindow.setVisible(false);
        NumberSignUpInput.setVisible(false);
        UsernameSignUpInput.setVisible(false);
        PasswordSignUpInput.setVisible(false);
        LoginFormWindow.setVisible(true);
        PasswordSigninInput1.setVisible(true);
        UsernameSigninInput1.setVisible(true);
    }//GEN-LAST:event_GOSigninWindowButtonActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        try {
        UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); // Change to whatever you like
    } catch (Exception e) {
        e.printStackTrace();
    }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccountInfoWindow;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Background1;
    private javax.swing.JLabel Background2;
    private javax.swing.JLabel Background3;
    private javax.swing.JButton BookButton1;
    private javax.swing.JButton BookButton2;
    private javax.swing.JButton BookButton3;
    private javax.swing.JLabel CompanyNameLabel;
    private javax.swing.JPanel Decoration1;
    private javax.swing.JButton ExitLoginButton1;
    private javax.swing.JButton ExitLoginButton2;
    private javax.swing.JButton ExitMenuButton;
    private javax.swing.JButton GOSigninWindowButton;
    private javax.swing.JPanel InfoWIndow2;
    private javax.swing.JPanel InfoWIndow3;
    private javax.swing.JPanel InfoWindow1;
    private javax.swing.JPanel LoginFormWindow;
    private javax.swing.JPanel LoginSystemPanel;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel MainPanel1;
    private javax.swing.JPanel MenuButtonsPanels;
    private javax.swing.JButton MenuOpenButton;
    private javax.swing.JTextField NumberSignUpInput;
    private javax.swing.JTextField PasswordSignUpInput;
    private javax.swing.JTextField PasswordSigninInput1;
    private javax.swing.JPanel RegisterFormWindow;
    private javax.swing.JButton RoomA1Button;
    private javax.swing.JButton RoomA1Button1;
    private javax.swing.JPanel RoomA1S;
    private javax.swing.JPanel RoomA2S;
    private javax.swing.JPanel RoomASelectionPanel;
    private javax.swing.JButton RoomB1Button;
    private javax.swing.JButton RoomB1Button1;
    private javax.swing.JPanel RoomB1S;
    private javax.swing.JPanel RoomB1S1;
    private javax.swing.JButton RoomB2Button;
    private javax.swing.JButton RoomB2Button1;
    private javax.swing.JPanel RoomB2S;
    private javax.swing.JPanel RoomB2S1;
    private javax.swing.JPanel RoomBSelectionPanel1;
    private javax.swing.JPanel RoomBSelectionPanel2;
    private javax.swing.JPanel RoomInfoPanel;
    private javax.swing.JButton RoomSectionButtion;
    private javax.swing.JPanel RoomSectionPanel;
    private javax.swing.JButton SignInButton1;
    private javax.swing.JButton SignInButton2;
    private javax.swing.JButton SignUpButton1;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel Title3;
    private javax.swing.JLabel UserNameGreetings;
    private javax.swing.JTextField UsernameSignUpInput;
    private javax.swing.JTextField UsernameSigninInput1;
    private javax.swing.JButton ViewHotelFeatureButton;
    private javax.swing.JButton ViewHotelFeatureButton1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    // End of variables declaration//GEN-END:variables

}
