/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bookinghotelsystem.MainPanel;


import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author Kevin
 */
public class MainWindow1 extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow1
     */
    public MainWindow1() {
        initComponents();
        
        MenuButtonsPanels.setVisible(false);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuButtonsPanels = new javax.swing.JPanel();
        UserNameGreetings = new javax.swing.JLabel();
        ViewHotelFeatureButton = new javax.swing.JButton();
        ExitMenuButton = new javax.swing.JButton();
        RoomSectionButtion = new javax.swing.JButton();
        ViewHotelFeatureButton1 = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        MainPanel1 = new javax.swing.JPanel();
        Decoration1 = new javax.swing.JPanel();
        jTextArea1 = new javax.swing.JTextArea();
        jTextArea3 = new javax.swing.JTextArea();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        Title1 = new javax.swing.JLabel();
        Title2 = new javax.swing.JLabel();
        Title3 = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        Background1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LoginSystemPanel = new javax.swing.JPanel();
        LoginSystemPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        ExitLoginButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        SignInButton = new javax.swing.JButton();
        RoomSectionPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        RoomBSelectionPanel2 = new javax.swing.JPanel();
        RoomB3S1 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        RoomB3Button1 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        RoomB2S1 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        RoomB2Button1 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        RoomB1S1 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        RoomB1Button1 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        RoomBSelectionPanel1 = new javax.swing.JPanel();
        RoomB3S = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        RoomB3Button = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        RoomB2S = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        RoomB2Button = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        RoomB1S = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        RoomB1Button = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        RoomASelectionPanel = new javax.swing.JPanel();
        RoomA3S = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        RoomA1Button2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        RoomA2S = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        RoomA1Button1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        RoomA1S = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RoomA1Button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        MenuOpenButton = new javax.swing.JButton();
        CompanyNameLabel = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuButtonsPanels.setBackground(new java.awt.Color(213, 208, 153, 200));
        MenuButtonsPanels.setPreferredSize(new java.awt.Dimension(250, 500));
        MenuButtonsPanels.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserNameGreetings.setBackground(new java.awt.Color(255, 255, 255));
        UserNameGreetings.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        UserNameGreetings.setForeground(new java.awt.Color(255, 255, 255));
        UserNameGreetings.setText("Username!");
        MenuButtonsPanels.add(UserNameGreetings, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 200, 20));

        ViewHotelFeatureButton.setBackground(new java.awt.Color(209, 199, 155));
        ViewHotelFeatureButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ViewHotelFeatureButton.setForeground(new java.awt.Color(255, 255, 255));
        ViewHotelFeatureButton.setText("Account/User");
        ViewHotelFeatureButton.setBorder(null);
        ViewHotelFeatureButton.setBorderPainted(false);
        ViewHotelFeatureButton.setContentAreaFilled(false);
        ViewHotelFeatureButton.setFocusPainted(false);
        ViewHotelFeatureButton.setFocusable(false);
        ViewHotelFeatureButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ViewHotelFeatureButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ViewHotelFeatureButton.setOpaque(true);
        ViewHotelFeatureButton.setRolloverEnabled(false);
        ViewHotelFeatureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewHotelFeatureButtonActionPerformed(evt);
            }
        });
        MenuButtonsPanels.add(ViewHotelFeatureButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 250, 40));

        ExitMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BookingHotelSystemIcons/Logo1-removebg-preview - 40x40.png"))); // NOI18N
        ExitMenuButton.setBorder(null);
        ExitMenuButton.setBorderPainted(false);
        ExitMenuButton.setContentAreaFilled(false);
        ExitMenuButton.setFocusPainted(false);
        ExitMenuButton.setFocusable(false);
        ExitMenuButton.setRolloverEnabled(false);
        ExitMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMenuButtonActionPerformed(evt);
            }
        });
        MenuButtonsPanels.add(ExitMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        RoomSectionButtion.setBackground(new java.awt.Color(209, 199, 155));
        RoomSectionButtion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        RoomSectionButtion.setForeground(new java.awt.Color(255, 255, 255));
        RoomSectionButtion.setText("Available Rooms");
        RoomSectionButtion.setBorder(null);
        RoomSectionButtion.setBorderPainted(false);
        RoomSectionButtion.setContentAreaFilled(false);
        RoomSectionButtion.setFocusPainted(false);
        RoomSectionButtion.setFocusable(false);
        RoomSectionButtion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RoomSectionButtion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RoomSectionButtion.setOpaque(true);
        RoomSectionButtion.setRolloverEnabled(false);
        RoomSectionButtion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomSectionButtionActionPerformed(evt);
            }
        });
        MenuButtonsPanels.add(RoomSectionButtion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 250, 40));

        ViewHotelFeatureButton1.setBackground(new java.awt.Color(209, 199, 155));
        ViewHotelFeatureButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ViewHotelFeatureButton1.setForeground(new java.awt.Color(255, 255, 255));
        ViewHotelFeatureButton1.setText("Hotel Essentials");
        ViewHotelFeatureButton1.setBorder(null);
        ViewHotelFeatureButton1.setBorderPainted(false);
        ViewHotelFeatureButton1.setContentAreaFilled(false);
        ViewHotelFeatureButton1.setFocusPainted(false);
        ViewHotelFeatureButton1.setFocusable(false);
        ViewHotelFeatureButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ViewHotelFeatureButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ViewHotelFeatureButton1.setOpaque(true);
        ViewHotelFeatureButton1.setRolloverEnabled(false);
        ViewHotelFeatureButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewHotelFeatureButton1ActionPerformed(evt);
            }
        });
        MenuButtonsPanels.add(ViewHotelFeatureButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 250, 40));

        jLabel43.setBackground(new java.awt.Color(255, 255, 255));
        jLabel43.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Welcome to Auqeza");
        MenuButtonsPanels.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 200, 20));

        getContentPane().add(MenuButtonsPanels, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        MainPanel1.setEnabled(false);
        MainPanel1.setOpaque(false);
        MainPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Decoration1.setPreferredSize(new java.awt.Dimension(750, 3));

        javax.swing.GroupLayout Decoration1Layout = new javax.swing.GroupLayout(Decoration1);
        Decoration1.setLayout(Decoration1Layout);
        Decoration1Layout.setHorizontalGroup(
            Decoration1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        Decoration1Layout.setVerticalGroup(
            Decoration1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        MainPanel1.add(Decoration1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 90, 760, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(204, 204, 204,0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Convenient location,\nfast Wi-Fi, and \nmeeting spaces for\nprofessionals on the\ngo.");
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setBorder(null);
        jTextArea1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTextArea1.setDoubleBuffered(true);
        jTextArea1.setFocusable(false);
        jTextArea1.setOpaque(false);
        MainPanel1.add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 240, -1));

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("Reliable room service, \ngyms, pools, dining \nareas pact with buffet\ndishes from \nprofessional chefs,\nsuitable for a guest's \ndaily needs.\n");
        jTextArea3.setAutoscrolls(false);
        jTextArea3.setBorder(null);
        jTextArea3.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTextArea3.setDoubleBuffered(true);
        jTextArea3.setFocusable(false);
        jTextArea3.setOpaque(false);
        MainPanel1.add(jTextArea3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 240, -1));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("Modern rooms, top \nnotch amenities,\nand breathtaking \nviews for a perfect \nview.\n");
        jTextArea2.setAutoscrolls(false);
        jTextArea2.setBorder(null);
        jTextArea2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTextArea2.setDoubleBuffered(true);
        jTextArea2.setFocusable(false);
        jTextArea2.setOpaque(false);
        MainPanel1.add(jTextArea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 240, -1));

        jButton1.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Find room");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        MainPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 180, 50));

        Title1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        Title1.setForeground(new java.awt.Color(248, 245, 222));
        Title1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Title1.setText("Luxury Escape");
        Title1.setPreferredSize(new java.awt.Dimension(300, 50));
        MainPanel1.add(Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 90, -1, -1));

        Title2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        Title2.setForeground(new java.awt.Color(248, 245, 222));
        Title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title2.setText("Features");
        Title2.setPreferredSize(new java.awt.Dimension(300, 50));
        MainPanel1.add(Title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 90, -1, -1));

        Title3.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        Title3.setForeground(new java.awt.Color(248, 245, 222));
        Title3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title3.setText("Business Hub");
        Title3.setPreferredSize(new java.awt.Dimension(300, 50));
        MainPanel1.add(Title3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        Title.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(248, 245, 222));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Welcome to Auqeza Suites");
        Title.setPreferredSize(new java.awt.Dimension(750, 50));
        MainPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 450, -1));

        Logo.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        Logo.setForeground(new java.awt.Color(248, 245, 222));
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BookingHotelSystemIcons/Logo1-removebg-preview - 40x40.png"))); // NOI18N
        Logo.setPreferredSize(new java.awt.Dimension(50, 50));
        MainPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 60, 50));

        Background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookinghotelsystem/PicturesforIcons/MainSystemPictures/Room View None.jpg"))); // NOI18N
        Background1.setPreferredSize(new java.awt.Dimension(1000, 500));
        MainPanel1.add(Background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setPreferredSize(new java.awt.Dimension(1000, 500));
        MainPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(MainPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        LoginSystemPanel.setBackground(new java.awt.Color(235, 231, 203));
        LoginSystemPanel.setPreferredSize(new java.awt.Dimension(1000, 500));
        LoginSystemPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginSystemPanel1.setBackground(new java.awt.Color(255, 255, 255));
        LoginSystemPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(182, 170, 147), 3));
        LoginSystemPanel1.setPreferredSize(new java.awt.Dimension(500, 300));
        LoginSystemPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField1.setText("Password: ");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 196, 173), 2));
        jTextField1.setPreferredSize(new java.awt.Dimension(250, 35));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        LoginSystemPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        jTextField2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField2.setText("Username:");
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 196, 173), 2));
        jTextField2.setPreferredSize(new java.awt.Dimension(250, 35));
        LoginSystemPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        ExitLoginButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ExitLoginButton.setText("Go back");
        ExitLoginButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(182, 174, 140), 2));
        ExitLoginButton.setPreferredSize(new java.awt.Dimension(100, 35));
        ExitLoginButton.setRequestFocusEnabled(false);
        ExitLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitLoginButtonActionPerformed(evt);
            }
        });
        LoginSystemPanel1.add(ExitLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jLabel12.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel12.setText("Sign in to Auqeza Suites");
        LoginSystemPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 270, 30));

        SignInButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        SignInButton.setText("Sign in");
        SignInButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(182, 174, 140), 2));
        SignInButton.setPreferredSize(new java.awt.Dimension(100, 35));
        SignInButton.setRequestFocusEnabled(false);
        LoginSystemPanel1.add(SignInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 190, -1, -1));

        LoginSystemPanel.add(LoginSystemPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        getContentPane().add(LoginSystemPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, -1, -1));

        RoomSectionPanel.setOpaque(false);
        RoomSectionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setOpaque(false);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(1000, 460));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setDoubleBuffered(false);
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(998, 1130));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RoomBSelectionPanel2.setBackground(new java.awt.Color(0, 0, 0));
        RoomBSelectionPanel2.setOpaque(false);
        RoomBSelectionPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RoomB3S1.setBackground(new java.awt.Color(238, 236, 200, 90));
        RoomB3S1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomPicturesABC/MainRoomA3s.jpg"))); // NOI18N
        jLabel29.setText("jLabel1");
        jLabel29.setPreferredSize(new java.awt.Dimension(200, 200));
        RoomB3S1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 200));

        RoomB3Button1.setBackground(new java.awt.Color(228, 223, 192));
        RoomB3Button1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RoomB3Button1.setForeground(new java.awt.Color(103, 102, 54));
        RoomB3Button1.setText("See room info");
        RoomB3Button1.setBorderPainted(false);
        RoomB3Button1.setFocusable(false);
        RoomB3Button1.setPreferredSize(new java.awt.Dimension(150, 25));
        RoomB3Button1.setRolloverEnabled(false);
        RoomB3S1.add(RoomB3Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, 30));

        jLabel30.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel30.setText("3 rooms Available");
        RoomB3S1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 20));

        jLabel31.setBackground(new java.awt.Color(238, 236, 200));
        jLabel31.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(238, 236, 200));
        jLabel31.setText("Cozy Business B");
        RoomB3S1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 30));

        jLabel32.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 255, 0));
        jLabel32.setText("₱ 2,499 per night");
        RoomB3S1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, 20));

        RoomBSelectionPanel2.add(RoomB3S1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, -1, -1));

        RoomB2S1.setBackground(new java.awt.Color(238, 236, 200, 90));
        RoomB2S1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomPicturesABC/MainRoomA2.jpg"))); // NOI18N
        jLabel33.setText("jLabel1");
        jLabel33.setPreferredSize(new java.awt.Dimension(200, 200));
        RoomB2S1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 200));

        RoomB2Button1.setBackground(new java.awt.Color(228, 223, 192));
        RoomB2Button1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RoomB2Button1.setForeground(new java.awt.Color(103, 102, 54));
        RoomB2Button1.setText("See room info");
        RoomB2Button1.setBorderPainted(false);
        RoomB2Button1.setFocusable(false);
        RoomB2Button1.setPreferredSize(new java.awt.Dimension(150, 25));
        RoomB2Button1.setRolloverEnabled(false);
        RoomB2S1.add(RoomB2Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, 30));

        jLabel34.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel34.setText("3 rooms Available");
        RoomB2S1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 20));

        jLabel35.setBackground(new java.awt.Color(238, 236, 200));
        jLabel35.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(238, 236, 200));
        jLabel35.setText("Double Business B");
        RoomB2S1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 30));

        jLabel36.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 255, 0));
        jLabel36.setText("₱ 2,499 per night");
        RoomB2S1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, 20));

        RoomBSelectionPanel2.add(RoomB2S1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        RoomB1S1.setBackground(new java.awt.Color(238, 236, 200, 90));
        RoomB1S1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomPicturesABC/MainRoomA1.jpg"))); // NOI18N
        jLabel37.setText("jLabel1");
        jLabel37.setPreferredSize(new java.awt.Dimension(200, 200));
        RoomB1S1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 200));

        RoomB1Button1.setBackground(new java.awt.Color(228, 223, 192));
        RoomB1Button1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RoomB1Button1.setForeground(new java.awt.Color(103, 102, 54));
        RoomB1Button1.setText("See room info");
        RoomB1Button1.setBorderPainted(false);
        RoomB1Button1.setFocusable(false);
        RoomB1Button1.setPreferredSize(new java.awt.Dimension(150, 25));
        RoomB1Button1.setRequestFocusEnabled(false);
        RoomB1Button1.setRolloverEnabled(false);
        RoomB1S1.add(RoomB1Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, 30));

        jLabel38.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel38.setText("3 rooms Available");
        RoomB1S1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 20));

        jLabel39.setBackground(new java.awt.Color(238, 236, 200));
        jLabel39.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(238, 236, 200));
        jLabel39.setText("Single Business B");
        RoomB1S1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 30));

        jLabel40.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 255, 0));
        jLabel40.setText("₱ 1,500 per night");
        RoomB1S1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, 20));

        RoomBSelectionPanel2.add(RoomB1S1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel41.setBackground(new java.awt.Color(238, 236, 200));
        jLabel41.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(238, 236, 200));
        jLabel41.setText("Luxury Exclusive Rooms");
        RoomBSelectionPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 820, 50));

        jPanel1.add(RoomBSelectionPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 740, 950, -1));

        RoomBSelectionPanel1.setBackground(new java.awt.Color(0, 0, 0));
        RoomBSelectionPanel1.setOpaque(false);
        RoomBSelectionPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RoomB3S.setBackground(new java.awt.Color(238, 236, 200, 90));
        RoomB3S.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomPicturesABC/MainRoomA3s.jpg"))); // NOI18N
        jLabel13.setText("jLabel1");
        jLabel13.setPreferredSize(new java.awt.Dimension(200, 200));
        RoomB3S.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 200));

        RoomB3Button.setBackground(new java.awt.Color(228, 223, 192));
        RoomB3Button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RoomB3Button.setForeground(new java.awt.Color(103, 102, 54));
        RoomB3Button.setText("See room info");
        RoomB3Button.setBorderPainted(false);
        RoomB3Button.setFocusable(false);
        RoomB3Button.setPreferredSize(new java.awt.Dimension(150, 25));
        RoomB3Button.setRolloverEnabled(false);
        RoomB3S.add(RoomB3Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, 30));

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel14.setText("3 rooms Available");
        RoomB3S.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 20));

        jLabel15.setBackground(new java.awt.Color(238, 236, 200));
        jLabel15.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(238, 236, 200));
        jLabel15.setText("Cozy Business B");
        RoomB3S.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 30));

        jLabel26.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 255, 0));
        jLabel26.setText("₱ 2,499 per night");
        RoomB3S.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, 20));

        RoomBSelectionPanel1.add(RoomB3S, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, -1, -1));

        RoomB2S.setBackground(new java.awt.Color(238, 236, 200, 90));
        RoomB2S.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomPicturesABC/MainRoomA2.jpg"))); // NOI18N
        jLabel16.setText("jLabel1");
        jLabel16.setPreferredSize(new java.awt.Dimension(200, 200));
        RoomB2S.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 200));

        RoomB2Button.setBackground(new java.awt.Color(228, 223, 192));
        RoomB2Button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RoomB2Button.setForeground(new java.awt.Color(103, 102, 54));
        RoomB2Button.setText("See room info");
        RoomB2Button.setBorderPainted(false);
        RoomB2Button.setFocusable(false);
        RoomB2Button.setPreferredSize(new java.awt.Dimension(150, 25));
        RoomB2Button.setRolloverEnabled(false);
        RoomB2S.add(RoomB2Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, 30));

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel17.setText("3 rooms Available");
        RoomB2S.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 20));

        jLabel18.setBackground(new java.awt.Color(238, 236, 200));
        jLabel18.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(238, 236, 200));
        jLabel18.setText("Double Business B");
        RoomB2S.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 30));

        jLabel27.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 255, 0));
        jLabel27.setText("₱ 2,499 per night");
        RoomB2S.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, 20));

        RoomBSelectionPanel1.add(RoomB2S, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        RoomB1S.setBackground(new java.awt.Color(238, 236, 200, 90));
        RoomB1S.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomPicturesABC/MainRoomA1.jpg"))); // NOI18N
        jLabel19.setText("jLabel1");
        jLabel19.setPreferredSize(new java.awt.Dimension(200, 200));
        RoomB1S.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 200));

        RoomB1Button.setBackground(new java.awt.Color(228, 223, 192));
        RoomB1Button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RoomB1Button.setForeground(new java.awt.Color(103, 102, 54));
        RoomB1Button.setText("See room info");
        RoomB1Button.setBorderPainted(false);
        RoomB1Button.setFocusable(false);
        RoomB1Button.setPreferredSize(new java.awt.Dimension(150, 25));
        RoomB1Button.setRequestFocusEnabled(false);
        RoomB1Button.setRolloverEnabled(false);
        RoomB1S.add(RoomB1Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, 30));

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel20.setText("3 rooms Available");
        RoomB1S.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 20));

        jLabel21.setBackground(new java.awt.Color(238, 236, 200));
        jLabel21.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(238, 236, 200));
        jLabel21.setText("Single Business B");
        RoomB1S.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 30));

        jLabel28.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 255, 0));
        jLabel28.setText("₱ 1,500 per night");
        RoomB1S.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, 20));

        RoomBSelectionPanel1.add(RoomB1S, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel22.setBackground(new java.awt.Color(238, 236, 200));
        jLabel22.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(238, 236, 200));
        jLabel22.setText("Business Class Rooms");
        RoomBSelectionPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 820, 50));

        jPanel1.add(RoomBSelectionPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 950, -1));

        RoomASelectionPanel.setBackground(new java.awt.Color(0, 0, 0));
        RoomASelectionPanel.setOpaque(false);
        RoomASelectionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RoomA3S.setBackground(new java.awt.Color(238, 236, 200, 90));
        RoomA3S.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomPicturesABC/MainRoomA3s.jpg"))); // NOI18N
        jLabel8.setText("jLabel1");
        jLabel8.setPreferredSize(new java.awt.Dimension(200, 200));
        RoomA3S.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 200));

        RoomA1Button2.setBackground(new java.awt.Color(228, 223, 192));
        RoomA1Button2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RoomA1Button2.setForeground(new java.awt.Color(103, 102, 54));
        RoomA1Button2.setText("See room info");
        RoomA1Button2.setBorderPainted(false);
        RoomA1Button2.setFocusable(false);
        RoomA1Button2.setPreferredSize(new java.awt.Dimension(150, 25));
        RoomA1Button2.setRolloverEnabled(false);
        RoomA3S.add(RoomA1Button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, 30));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setText("3 rooms Available");
        RoomA3S.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 20));

        jLabel10.setBackground(new java.awt.Color(238, 236, 200));
        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(238, 236, 200));
        jLabel10.setText("Cozy Class A");
        RoomA3S.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 30));

        jLabel25.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 255, 0));
        jLabel25.setText("₱ 2,499 per night");
        RoomA3S.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, 20));

        RoomASelectionPanel.add(RoomA3S, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, -1, -1));

        RoomA2S.setBackground(new java.awt.Color(238, 236, 200, 90));
        RoomA2S.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomPicturesABC/MainRoomA2.jpg"))); // NOI18N
        jLabel5.setText("jLabel1");
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 200));
        RoomA2S.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 200));

        RoomA1Button1.setBackground(new java.awt.Color(228, 223, 192));
        RoomA1Button1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RoomA1Button1.setForeground(new java.awt.Color(103, 102, 54));
        RoomA1Button1.setText("See room info");
        RoomA1Button1.setBorderPainted(false);
        RoomA1Button1.setFocusable(false);
        RoomA1Button1.setPreferredSize(new java.awt.Dimension(150, 25));
        RoomA1Button1.setRolloverEnabled(false);
        RoomA2S.add(RoomA1Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, 30));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("3 rooms Available");
        RoomA2S.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 20));

        jLabel7.setBackground(new java.awt.Color(238, 236, 200));
        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(238, 236, 200));
        jLabel7.setText("Double Class A");
        RoomA2S.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 30));

        jLabel24.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 255, 0));
        jLabel24.setText("₱ 2,499 per night");
        RoomA2S.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, 20));

        RoomASelectionPanel.add(RoomA2S, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        RoomA1S.setBackground(new java.awt.Color(238, 236, 200, 90));
        RoomA1S.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomPicturesABC/MainRoomA1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 200));
        RoomA1S.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 200));

        RoomA1Button.setBackground(new java.awt.Color(228, 223, 192));
        RoomA1Button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RoomA1Button.setForeground(new java.awt.Color(103, 102, 54));
        RoomA1Button.setText("See room info");
        RoomA1Button.setBorderPainted(false);
        RoomA1Button.setFocusable(false);
        RoomA1Button.setPreferredSize(new java.awt.Dimension(150, 25));
        RoomA1Button.setRequestFocusEnabled(false);
        RoomA1Button.setRolloverEnabled(false);
        RoomA1S.add(RoomA1Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, 30));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("3 rooms Available");
        RoomA1S.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 20));

        jLabel4.setBackground(new java.awt.Color(238, 236, 200));
        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(238, 236, 200));
        jLabel4.setText("Single Class A");
        RoomA1S.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 30));

        jLabel23.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 255, 0));
        jLabel23.setText("₱ 1,500 per night");
        RoomA1S.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, 20));

        RoomASelectionPanel.add(RoomA1S, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel11.setBackground(new java.awt.Color(238, 236, 200));
        jLabel11.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(238, 236, 200));
        jLabel11.setText("Class A Rooms");
        RoomASelectionPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 820, 50));

        jPanel1.add(RoomASelectionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0, 70));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1140, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane2.setViewportView(jPanel1);

        RoomSectionPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        MenuOpenButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BookingHotelSystemIcons/Logo1-removebg-preview - 40x40.png"))); // NOI18N
        MenuOpenButton.setBorder(null);
        MenuOpenButton.setBorderPainted(false);
        MenuOpenButton.setContentAreaFilled(false);
        MenuOpenButton.setFocusPainted(false);
        MenuOpenButton.setFocusable(false);
        MenuOpenButton.setRolloverEnabled(false);
        MenuOpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOpenButtonActionPerformed(evt);
            }
        });
        RoomSectionPanel.add(MenuOpenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        CompanyNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        CompanyNameLabel.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        CompanyNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        CompanyNameLabel.setText("Auqeza Suites");
        RoomSectionPanel.add(CompanyNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 820, 40));

        Background.setBackground(new java.awt.Color(0, 0, 0));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookinghotelsystem/PicturesforIcons/MainSystemPictures/Room View Main Intro Blurred100.jpg"))); // NOI18N
        Background.setPreferredSize(new java.awt.Dimension(1000, 500));
        RoomSectionPanel.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(RoomSectionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Book button on Start
        jScrollPane2.setVisible(false);
        RoomSectionPanel.setVisible(true);
        MainPanel1.setVisible(false);
        jButton1.setVisible(false);
        
        Timer timer1 = new Timer(500, e -> {
            jScrollPane2.setVisible(true);
            jScrollPane2.setOpaque(false);
            jScrollPane2.getViewport().setOpaque(false);
        });
        timer1.setRepeats(false);
        timer1.start();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void ViewHotelFeatureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewHotelFeatureButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewHotelFeatureButtonActionPerformed

    private void RoomSectionButtionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomSectionButtionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomSectionButtionActionPerformed

    private void ViewHotelFeatureButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewHotelFeatureButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewHotelFeatureButton1ActionPerformed

    private void ExitMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuButtonActionPerformed
        MenuButtonsPanels.setVisible(false);
        CompanyNameLabel.setVisible(true);
    }//GEN-LAST:event_ExitMenuButtonActionPerformed

    private void MenuOpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOpenButtonActionPerformed
        MenuButtonsPanels.setVisible(true);
        CompanyNameLabel.setVisible(false);
    }//GEN-LAST:event_MenuOpenButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void ExitLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitLoginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitLoginButtonActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        try {
        UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); // Change to whatever you like
    } catch (Exception e) {
        e.printStackTrace();
    }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Background1;
    private javax.swing.JLabel CompanyNameLabel;
    private javax.swing.JPanel Decoration1;
    private javax.swing.JButton ExitLoginButton;
    private javax.swing.JButton ExitMenuButton;
    private javax.swing.JPanel LoginSystemPanel;
    private javax.swing.JPanel LoginSystemPanel1;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel MainPanel1;
    private javax.swing.JPanel MenuButtonsPanels;
    private javax.swing.JButton MenuOpenButton;
    private javax.swing.JButton RoomA1Button;
    private javax.swing.JButton RoomA1Button1;
    private javax.swing.JButton RoomA1Button2;
    private javax.swing.JPanel RoomA1S;
    private javax.swing.JPanel RoomA2S;
    private javax.swing.JPanel RoomA3S;
    private javax.swing.JPanel RoomASelectionPanel;
    private javax.swing.JButton RoomB1Button;
    private javax.swing.JButton RoomB1Button1;
    private javax.swing.JPanel RoomB1S;
    private javax.swing.JPanel RoomB1S1;
    private javax.swing.JButton RoomB2Button;
    private javax.swing.JButton RoomB2Button1;
    private javax.swing.JPanel RoomB2S;
    private javax.swing.JPanel RoomB2S1;
    private javax.swing.JButton RoomB3Button;
    private javax.swing.JButton RoomB3Button1;
    private javax.swing.JPanel RoomB3S;
    private javax.swing.JPanel RoomB3S1;
    private javax.swing.JPanel RoomBSelectionPanel1;
    private javax.swing.JPanel RoomBSelectionPanel2;
    private javax.swing.JButton RoomSectionButtion;
    private javax.swing.JPanel RoomSectionPanel;
    private javax.swing.JButton SignInButton;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel Title3;
    private javax.swing.JLabel UserNameGreetings;
    private javax.swing.JButton ViewHotelFeatureButton;
    private javax.swing.JButton ViewHotelFeatureButton1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
